"""
Django settings for ai_listing_project project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "")
if not SECRET_KEY:
    if os.environ.get("DEBUG", "true").lower() in ("1", "true", "yes"):
        SECRET_KEY = "django-insecure-local-dev-only"
    else:
        raise RuntimeError("生产环境请设置环境变量 SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# 置于 Nginx 等反向代理之后时识别真实 Host / HTTPS
USE_X_FORWARDED_HOST = os.environ.get("USE_X_FORWARDED_HOST", "false").lower() in (
    "1",
    "true",
    "yes",
)
if os.environ.get("USE_X_FORWARDED_PROTO", "false").lower() in ("1", "true", "yes"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai_listing_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                os.path.join(BASE_DIR, 'myapp/templates')
        ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.pending_approval_badge',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_listing_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 兼容 Docker 场景：优先读 DB_*，缺失时回退到 MYSQL_*。
        'NAME': os.environ.get('DB_NAME') or os.environ.get('MYSQL_DATABASE', 'ai_listing'),
        'USER': os.environ.get('DB_USER') or os.environ.get('MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD') or os.environ.get('MYSQL_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

_static_dir = BASE_DIR / 'static'
STATICFILES_DIRS = [_static_dir] if _static_dir.is_dir() else []
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Docker 等生产环境无 DEBUG 时仍可通过 Django 提供 media（内网部署）
SERVE_MEDIA = os.environ.get("SERVE_MEDIA", "true").lower() in ("1", "true", "yes")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/ai_listing/login'
LOGIN_REDIRECT_URL = '/ai_listing/original_text'
LOGOUT_REDIRECT_URL = '/ai_listing/login'

# ---------- 邮件（忘记密码等）：QQ 邮箱 ----------
# QQ 邮箱：smtp.qq.com，端口 465（SSL）或 587（STARTTLS），密码填「授权码」非 QQ 登录密码。
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.qq.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '').lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', '1').lower() not in ('0', 'false', 'no')
if EMAIL_PORT == 587 and not EMAIL_USE_TLS:
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
elif EMAIL_PORT == 465 and not EMAIL_USE_TLS:
    EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@example.com')


# OpenAI / 兼容代理（通过环境变量注入密钥）
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_BASE_URL = os.environ.get("OPENAI_BASE_URL", "https://api.openai-proxy.org/v1")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-5.1")
# 单次 HTTP「读取响应」超时（秒）。SDK 默认整体约 600s，长 Listing 分析易触发 Request timed out。
OPENAI_READ_TIMEOUT = float(os.environ.get("OPENAI_READ_TIMEOUT", "1200"))
OPENAI_CONNECT_TIMEOUT = float(os.environ.get("OPENAI_CONNECT_TIMEOUT", "60"))
# 视觉模型（主图 / A+ 图需分析，须支持 image_url）
OPENAI_VISION_MODEL = os.environ.get("OPENAI_VISION_MODEL", "gpt-4o")
AI_IMAGE_NEED_MAX_IMAGES_MAIN = int(os.environ.get("AI_IMAGE_NEED_MAX_IMAGES_MAIN", "8"))
AI_IMAGE_NEED_MAX_IMAGES_APLUS = int(os.environ.get("AI_IMAGE_NEED_MAX_IMAGES_APLUS", "15"))

# Nano Banana 生图 API（script/nano_banana_api.py）
NANO_BANANA_API_URL = os.environ.get("NANO_BANANA_API_URL", "https://grsai.dakka.com.cn/v1/api/generate")
# 仅填 sk-...，不要带 Bearer 前缀（代码会自动加）
NANO_BANANA_API_KEY = os.environ.get("NANO_BANANA_API_KEY", "")
# 每个图需模块生成张数（如主图、副图1 各 3 张）
NANO_BANANA_IMAGES_PER_MODULE = int(os.environ.get("NANO_BANANA_IMAGES_PER_MODULE", "3"))
# 全局并行 API 数（可同时跑 2 个模块 × 每模块 3 张 = 6）
NANO_BANANA_MODULE_WORKERS = int(os.environ.get("NANO_BANANA_MODULE_WORKERS", "6"))
# 每位用户独立的 GrsAi 并行路数（默认 6，与每批 MODULE_WORKERS 一致）
NANO_BANANA_API_SEMAPHORE_PER_USER = int(os.environ.get("NANO_BANANA_API_SEMAPHORE_PER_USER", "6"))
# 全站 GrsAi 并行上限，槽位满后排队（建议 PER_USER × 同时在线生图用户数）
NANO_BANANA_API_SEMAPHORE_GLOBAL = int(os.environ.get("NANO_BANANA_API_SEMAPHORE_GLOBAL", "24"))
# 兼容旧名：等同每用户并行路数
NANO_BANANA_API_SEMAPHORE = int(os.environ.get("NANO_BANANA_API_SEMAPHORE", "6"))
NANO_BANANA_HTTP_RETRIES = int(os.environ.get("NANO_BANANA_HTTP_RETRIES", "1"))
NANO_BANANA_BATCH_STAGGER_SEC = float(os.environ.get("NANO_BANANA_BATCH_STAGGER_SEC", "0"))
# 失败后不补全、不重试占满槽位
NANO_BANANA_ENABLE_TOPUP = os.environ.get("NANO_BANANA_ENABLE_TOPUP", "false").lower() in (
    "1",
    "true",
    "yes",
)
NANO_BANANA_BATCH_USE_THREADS = os.environ.get("NANO_BANANA_BATCH_USE_THREADS", "true").lower() in (
    "1",
    "true",
    "yes",
)
# 生图失败不重试（1 = 只请求一次）
NANO_BANANA_VARIANT_MAX_RETRIES = int(os.environ.get("NANO_BANANA_VARIANT_MAX_RETRIES", "1"))
NANO_BANANA_VARIANT_RETRY_DELAY = float(os.environ.get("NANO_BANANA_VARIANT_RETRY_DELAY", "2"))
NANO_BANANA_HTTP_TIMEOUT = float(os.environ.get("NANO_BANANA_HTTP_TIMEOUT", "360"))
NANO_BANANA_POLL_MAX_WAIT = float(os.environ.get("NANO_BANANA_POLL_MAX_WAIT", "360"))
NANO_BANANA_POLL_INTERVAL = float(os.environ.get("NANO_BANANA_POLL_INTERVAL", "2"))
NANO_BANANA_PARALLEL_VARIANTS = os.environ.get("NANO_BANANA_PARALLEL_VARIANTS", "true").lower() in (
    "1",
    "true",
    "yes",
)
# 产品原生图：优先 media 公网 URL；未配置时本地图用 base64（带进程内缓存）
# 主图-副图 / A+ 场景图仅使用 https Listing URL，不受此项影响
NANO_BANANA_PREFER_URL_REFS = os.environ.get("NANO_BANANA_PREFER_URL_REFS", "true").lower() in (
    "1",
    "true",
    "yes",
)
# 可选：原生图走 URL 时的 media 根（例 http://192.168.x.x:8000/media）
NANO_BANANA_MEDIA_PUBLIC_BASE = os.environ.get("NANO_BANANA_MEDIA_PUBLIC_BASE", "").strip()
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "").strip()
NANO_BANANA_NATIVE_MAX_REFS = int(os.environ.get("NANO_BANANA_NATIVE_MAX_REFS", "2"))
NANO_BANANA_SCENE_MAX_REFS = int(os.environ.get("NANO_BANANA_SCENE_MAX_REFS", "4"))
NANO_BANANA_TOPUP_MAX_ROUNDS = int(os.environ.get("NANO_BANANA_TOPUP_MAX_ROUNDS", "30"))

# Amazon 商品图 webhook（AI 生图页「获取图片」）
AMAZON_IMAGE_WEBHOOK_URL = os.environ.get("AMAZON_IMAGE_WEBHOOK_URL", "")
