# Generated by Django 5.2.13 on 2026-04-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsinAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20, unique=True, verbose_name='ASIN')),
                ('listing', models.TextField(verbose_name='Listing 信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('refus', 'Refus'), ('negative', '差评和未被满足'), ('voc', 'VOC'), ('suggestions', '五条差异化建议')], max_length=20, verbose_name='维度类别')),
                ('gpt_summary', models.TextField(verbose_name='GPT 总结与优化')),
                ('satisfy_condition', models.TextField(verbose_name='满足条件')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.asinanalysis')),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('analysis', 'category')},
            },
        ),
    ]
