# Generated by Django 5.2.13 on 2026-04-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalAsinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20, unique=True, verbose_name='ASIN')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='关键词')),
                ('ask_rufus', models.JSONField(blank=True, default=dict, verbose_name='Ask Rufus')),
                ('voc', models.JSONField(blank=True, default=dict, verbose_name='VOC 原始数据(JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
