# Generated by Django 5.2.13 on 2026-04-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_refus_to_rufus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdetail',
            name='category',
            field=models.CharField(choices=[('rufus', 'Rufus'), ('negative', '差评和未被满足'), ('voc', 'VOC'), ('suggestions', '五条差异化建议')], max_length=20, verbose_name='维度类别'),
        ),
    ]
