# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_analysisdetail_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="originalasindata",
            name="asin_cluster",
            field=models.JSONField(blank=True, default=list, verbose_name="ASIN 集群"),
        ),
    ]
