# Generated by Django 5.2.13 on 2026-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_analysisdetail_category_voc_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalasindata',
            name='cluster_suggestion_edited',
            field=models.TextField(blank=True, default='', verbose_name='差异化建议(可编辑)'),
        ),
        migrations.AddField(
            model_name='originalasindata',
            name='material_supplement',
            field=models.TextField(blank=True, default='待定', verbose_name='材质与补充'),
        ),
        migrations.AddField(
            model_name='originalasindata',
            name='negative_direction_edited',
            field=models.TextField(blank=True, default='', verbose_name='差评改进方向(可编辑)'),
        ),
        migrations.AddField(
            model_name='originalasindata',
            name='voc_positioning_edited',
            field=models.TextField(blank=True, default='', verbose_name='VOC定位(可编辑)'),
        ),
    ]
