from django.urls import path

from . import views

urlpatterns = [
    path('index', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('register', views.register_view, name='register'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('password-reset/confirm/', views.password_reset_confirm_view, name='password_reset_confirm'),
    path('captcha/image/', views.captcha_image, name='captcha_image'),
    path('logout', views.logout_view, name='logout'),
    path('account/settings', views.account_settings, name='account_settings'),
    path('ai_listing', views.ai_listing, name='ai_listing'),
    path('ai_listing/history/<str:asin>', views.ai_listing_history_json, name='ai_listing_history'),
    path('ai_image_gen', views.ai_image_gen, name='ai_image_gen'),
    path('ai_image_gen/fetch_images', views.ai_image_fetch_images, name='ai_image_fetch_images'),
    path('ai_image_gen/save_original', views.ai_image_save_original_json, name='ai_image_save_original_json'),
    path('ai_image_gen/upload_original', views.ai_image_upload_original_json, name='ai_image_upload_original_json'),
    path('ai_image_gen/generate_need', views.ai_image_generate_need, name='ai_image_generate_need'),
    path('ai_image_gen/batch_generate', views.ai_image_batch_generate, name='ai_image_batch_generate'),
    path('ai_image_gen/generate_plan', views.ai_image_generate_plan, name='ai_image_generate_plan'),
    path('ai_image_gen/generate_all', views.ai_image_generate_all, name='ai_image_generate_all'),
    path('ai_image_gen/generate_wave', views.ai_image_generate_wave, name='ai_image_generate_wave'),
    path('ai_image_gen/run_job', views.ai_image_run_generation_job, name='ai_image_run_generation_job'),
    path('ai_image_gen/run_jobs_batch', views.ai_image_run_jobs_batch, name='ai_image_run_jobs_batch'),
    path('ai_image_gen/run_custom_module', views.ai_image_run_custom_module, name='ai_image_run_custom_module'),
    path('ai_image_gen/generate_module', views.ai_image_generate_module, name='ai_image_generate_module'),
    path('ai_image_gen/topup_modules', views.ai_image_topup_modules, name='ai_image_topup_modules'),
    path('ai_image_gen/topup_chunk', views.ai_image_topup_chunk, name='ai_image_topup_chunk'),
    path('ai_image_gen/save_finished', views.ai_image_save_finished_json, name='ai_image_save_finished_json'),
    path('ai_image_gen/upload_finished', views.ai_image_upload_finished_json, name='ai_image_upload_finished_json'),
    path('ai_image_gen/optimize_finished', views.ai_image_optimize_finished, name='ai_image_optimize_finished'),
    path('ai_image_gen/download_finished', views.ai_image_download_finished, name='ai_image_download_finished'),
    path('gpt_analysis', views.gpt_analysis, name='gpt_analysis'),
    path('analysis_list', views.analysis_list, name='analysis_list'),
    path('listing_panel', views.listing_panel, name='listing_panel'),
    path('analysis_list/batch_delete', views.batch_delete_analysis, name='batch_delete_analysis'),
    path('analysis_list/<str:asin>/delete', views.delete_analysis_row, name='delete_analysis_row'),
    path('original_text', views.original_text_list, name='original_text_list'),
    path('data_fetch', views.data_fetch, name='data_fetch'),
    path('users', views.user_manage, name='user_manage'),
    path('users/<int:user_id>/toggle_active', views.toggle_user_active, name='toggle_user_active'),
    path('users/<int:user_id>/delete', views.delete_user, name='delete_user'),
    path('approvals', views.approval_list, name='approval_list'),
    path('approvals/<int:user_id>/<str:action>', views.approval_action, name='approval_action'),
    path('original_text/import_voc', views.import_voc, name='import_voc'),
    path('original_text/import_voc_cluster', views.import_voc_cluster, name='import_voc_cluster'),
    path('original_text/batch_delete', views.batch_delete_original_text, name='batch_delete_original_text'),
    path('original_text/<str:asin>/delete', views.delete_original_text_row, name='delete_original_text_row'),
    path('original_text/<str:asin>/refresh_ask_rufus', views.refresh_ask_rufus, name='refresh_ask_rufus'),
    path('original_text/<str:asin>/refresh_keywords', views.refresh_keywords, name='refresh_keywords'),
    path('original_text/<str:asin>/refresh_asin_cluster', views.refresh_asin_cluster, name='refresh_asin_cluster'),
    path('original_text/<str:asin>/save_asin_cluster', views.save_asin_cluster, name='save_asin_cluster'),
    path('original_text/<str:asin>/assign', views.assign_original_asin, name='assign_original_asin'),

]